///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2018 Oracle and/or its affiliates. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= 快速入门示例
:description: Helidon 快速入门
:keywords: helidon

有两个快速入门示例，一个用于Helidon SE，另一个用于Helidon MP（MicroProfile）。
使用Maven模版生成示例。生成的Maven项目中包含对Docker和Kubernetes的支持。

== 前置条件

如果您还没有准备好环境配置等条件，请确保您已满足<<getting-started/01_prerequisites.adoc,系统前置条件>>

== 生成工程

使用Helidon Maven模版中的一个（或两个）生成项目源码。这两个示例都产生了支持相同REST API的REST服务，但它们以不同方式实现：

1. Helidon SE示例直接使用Helidon WebServer组件实现REST服务。它展示了配置WebServer和实现基本路由规则的基础知识。
2. Helidon MP示例使用Helidon MicroProfile服务器提供的JAX-RS支持实现REST服务。

[source,bash,subs="attributes+"]
.Helidon SE 样例
----
mvn archetype:generate -DinteractiveMode=false \
    -DarchetypeGroupId=io.helidon.archetypes \
    -DarchetypeArtifactId=helidon-quickstart-se \
    -DarchetypeVersion={helidon-version} \
    -DgroupId=io.helidon.样例s \
    -DartifactId=quickstart-se \
    -Dpackage=io.helidon.样例s.quickstart.se
----

[source,bash,subs="attributes+"]
.Helidon MP 样例
----
mvn archetype:generate -DinteractiveMode=false \
    -DarchetypeGroupId=io.helidon.archetypes \
    -DarchetypeArtifactId=helidon-quickstart-mp \
    -DarchetypeVersion={helidon-version} \
    -DgroupId=io.helidon.样例s \
    -DartifactId=quickstart-mp \
    -Dpackage=io.helidon.样例s.quickstart.mp
----

模版在当前目录中生成Maven项目（比如，quickstart-mp）。切换到此目录：

[source,bash]
----
cd quickstart-*
----

TIP: 如果要将生成的项目用作自己应用程序的启动器，那么你可以用适合你的应用程序的值替换groupId，artifactId和package。

== 构建此应用程序

比如：

[source,bash]
----
mvn package
----

== 运行此应用程序

该项目为该示例构建了一个应用程序jar，并将所有运行时依赖项保存在`target/libs`目录中。
这意味着您可以通过运行应用程序生成的jar文件轻松启动应用程序：

[source,bash]
.Helidon SE 样例
----
java -jar target/quickstart-se.jar
----

[source,bash]
.Helidon MP 样例
----
java -jar target/quickstart-mp.jar
----

== 试试运行的应用程序

这两个示例都支持相同的REST接口，因此您以相同的方式尝试这两个示例。

该示例是一个非常简单的“Hello World”问候语服务。它支持生成问候消息的GET请求，以及更改问候语本身的PUT请求。
请求响应使用JSON格式进行编码。例如：

```
curl -X GET http://localhost:8080/greet
{"message":"Hello World!"}

curl -X GET http://localhost:8080/greet/Joe
{"message":"Hello Joe!"}

curl -X PUT http://localhost:8080/greet/greeting/Hola
{"greeting":"Hola"}

curl -X GET http://localhost:8080/greet/Jose
{"message":"Hola Jose!"}
```

== 构建Docker镜像

该项目还包含一个Dockerfile，因此您可以轻松地构建和运行docker镜像。
因为示例的运行时依赖性已经在`target/libs`中，所以Dockerfile非常简单（参考`target/Dockerfile`）。
要构建Docker镜像，您需要在系统上安装并确保Docker处于运行状态。

[source,bash]
.Helidon SE 样例
----
docker build -t quickstart-se target
----

[source,bash]
.Helidon MP 样例
----
docker build -t quickstart-mp target
----

== 运行Docker镜像

[source,bash]
.Helidon SE 样例
----
docker run --rm -p 8080:8080 quickstart-se:latest
----

[source,bash]
.Helidon MP 样例
----
docker run --rm -p 8080:8080 quickstart-mp:latest
----

然后您可以像以前一样尝试应用程序。

[[deploy-to-k8s]]
== 将此应用程序发布至Kubernetes

如果您无权访问Kubernetes群集，则可以<<getting-started/04_kubernetes.adoc,在本地电脑桌面上安装一个群集>>。
然后发布这个样例程序：

[source,bash]
.验证与群集的连接
----
kubectl cluster-info
kubectl get nodes
----

[source,bash]
.将应用程序部署到Kubernetes
----
kubectl create -f target/app.yaml
kubectl get pods                    # 等待启动pod运行
----

== 在Kubernetes上运用应用程序

启动Kubernetes代理服务器，以便您可以通过localhost连接到您的服务：

[source,bash]
.启动kubctl代理
----
kubectl proxy
----

接下来获取服务的信息。

[source,bash]
.Helidon SE 样例
----
kubectl get service quickstart-se
----

[source,bash]
.Helidon MP 样例
----
kubectl get service quickstart-mp
----

注意端口号。您现在可以像以前一样使用应用程序，但这里是使用第二个端口号（NodePort）而不是8080.例如：

```
curl -X GET http://localhost:31431/greet
```

当你完成练习后，记得清理。

[source,bash]
.从Kubernetes中删除该应用程序
----
kubectl delete -f target/app.yaml
----

