///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2018 Oracle and/or its affiliates. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= 管理依赖
:description: Managing Maven dependencies
:keywords: bom, dependency management

Helidon提供了"`Bill Of Materials`" (BOM)来管理依赖。
这是一个提供了管理依赖的的特殊maven的pom文件。

使用Helidon BOM允许我们通过Helison的版本信息来使用Helidon的组件们。

== Helidon的BOM和POM


将以下代码段添加到pom.xml文件中, 以此来导入Helidon BOM。

[source,xml,subs="attributes+"]
.导入Helidon BOM
----
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>io.helidon</groupId>
            <artifactId>helidon-bom</artifactId>
            <version>{helidon-version}</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>
----

== 使用Helidon组件依赖项

导入BOM后，可以在不指定版本的情况下声明Helidon组件的依赖关系。

[source,xml]
.组件依赖
----
<dependency>
    <groupId>io.helidon.webserver</groupId>
    <artifactId>helidon-webserver</artifactId>
</dependency>
----
