///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2018 Oracle and/or its affiliates. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Kubernetes开发环境
:description: Running Kubernetes on your desktop.
:keywords: kubernetes

对于开发人员来将，通常会在个人电脑上面运行Kubernetes环境，两种流行的方法是在Docker for Desktop中使用 https://kubernetes.io/docs/getting-started-guides/minikube/[Kubernetes Minikube] 或 https://docs.docker.com/docker-for-mac/kubernetes/[Kubernetes Docker桌面版支持]。

在本指南中，我们将使用 https://docs.docker.com/docker-for-mac/kubernetes/[Kubernetes Docker桌面版支持].

== 安装

安装适用于 https://docs.docker.com/docker-for-mac/install/[Mac的Docker] 或适用于 https://docs.docker.com/docker-for-windows/install/[Windows的Docker]。

要使用Kubernetes支持，您需要获得Edge Channel安装程序。

== 启用Kubernetes支持

启用
https://docs.docker.com/docker-for-mac/#kubernetes[Kubernetes Support for Mac]
或者
https://docs.docker.com/docker-for-windows/#kubernetes[Kubernetes Support for Windows].

Kubernetes安装完成后，请确保正确设置上下文以使用docker-for-desktop。

[source,bash]
.确保将K8s上下文设置为docker-for-desktop
----
kubectl config get-contexts
kubectl config use-context docker-for-desktop
kubectl cluster-info
kubectl version --short
kubectl get nodes
----

== 继续 <<getting-started/02_base-example.adoc#deploy-to-k8s,快速入门示例>>
