///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2018 Oracle and/or its affiliates. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

:javadoc-base-url-api: {javadoc-base-url}?io/helidon/config

= 加载配置：配置源和解析器
:description: A summary of Helidon config sources and parsers
:keywords: Helidon, config, sources, parsers

可以从不同位置加载不同格式表示的配置。本节介绍应用程序如何使用配置源和配置解析器来加载配置数据。

== 总览
每个配置源从特定类型的位置读取数据，但是并不考虑那里的配置数据的格式。
每个配置解析器将以特定格式表示的数据转换为配置系统其余部分使用的内存中配置数据结构，而不关心数据所在的位置或物理检索方式。
将给定格式准备数据在给定系统的给定位置进行协同工作。
当您的应用程序准备 `Config.Builder` 时，它会设置构建器在构造生成的 `Config` 对象时应使用的 `ConfigSource` 和 `ConfigParser` 。


== 配置来源
如果您的应用程序使用默认配置，则配置系统会自动为您设置配置源，如 <<config/01_introduction.adoc#config-sources-default-config,配置简介>> 中所述。
如果您的应用程序使用 link:{javadoc-base-url-api}/Config.Builder.html[`Config.Builder`]，那么它可以调用该构建器上的某个源方法来设置它应该使用的配置源。

配置系统包括对几种配置源的支持，例如：

* 运行时类路径上的资源，
* 环境变量，
* 一份文件，
* Java系统属性，
* 一个URL，
* 各种内存数据结构 (`String`, `Map`, `Properties`)

有关内置配置源类型的完整列表以及如何使用它们，请参阅 link:{javadoc-base-url-api}/ConfigSources.html[`ConfigSources`] 类的Java文档。

您还可以通过实现 link:{javadoc-base-url-api}/spi/ConfigSource.html[`ConfigSource`] 接口来扩展配置系统以处理其他类型的源。
有关完整信息，请参阅<<config/07_extensions.adoc,扩展>>文档。

有关配置源的一些更复杂的方面的详细信息，请参阅 <<config/06_advanced-configuration.adoc,高级主题>> 页面。

== 配置解析器
当它从源读取配置文本时，配置系统使用配置解析器将该文本转换为表示该配置的内存数据结构。
配置系统包括几个内置解析器，例如Java属性，YAML，JSON和HOCON格式。
请参阅<<config/01_introduction.adoc#built-in-formats,介绍中的此部分>>，了解如何更改 `pom.xml` 以使应用程序可以使用这些格式的解析器。
之后，您的应用程序可以调用link:{javadoc-base-url-api}/Config.Builder.html#addParser-io.helidon.config.spi.ConfigParser-[配置构建器 `addParser`]方法，构建器将使用您选择的解析器。

您可以使用自己的自定义解析器扩展系统。
实现 `ConfigParser` 接口，然后使用 `addParser` 方法构造 `Config.Builder`，传递客户解析器的实例。
调用其中一个 `sources` 方法以包含使用自定义格式的源，然后构建 `Config对象。

== 检测和响应配置数据的变化
配置系统返回给您的应用程序的每个 `Config` 对象都是不可变的。即使其中一个底层配置源中的信息发生更改，从早期内容构建的内存数据结构也保持不变。

即便如此，配置系统允许您的应用程序了解数据中发生的这些潜在变化何时发生并做出相应响应。<<config/05_mutability-support.adoc,可变性>>部分详细解释了这一点，link:{javadoc-base-url-api}/PollingStrategies.html[`PollingStrategies`] Java 文档描述了其内置实现。

== 处理加载错误：重试策略 [[retry]]
配置源，尤其是那些依赖于易错机制（如网络或共享文件系统）的源，可能无法在短暂停机期间加载。
配置系统允许您为应用程序使用依赖于此类技术的配置构建弹性。

当您的应用程序构建 `ConfigSource` 时，可以指定 _重试策略_ 。该策略不仅负责加载数据，还负责在加载期间检测错误并实施算法，以便在将故障报告回应用程序之前决定重试失败负载的次数和次数。

配置系统包括两个预定义的重试策略：

.预定义的重试策略
|===
|策略 | 总结

|"just call" (default) |要求配置源加载数据而不重试
|"repeat" |执行可设置数量的基于时间的重试，仅在所有可用重试失败后报告失败
|===
有关这些内置重试策略的完整详细信息，link:{javadoc-base-url-api}/RetryPolicies.html[`RetryPolicies`] JavaDoc。

您可以制定自己的策略。实现link:{javadoc-base-url-api}/spi/RetryPolicy.html[`RetryPolicy`]接口。然后将策略实现的实例传递给配置源构建器的 `retryPolicy` 方法。

