///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2018 Oracle and/or its affiliates. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Microprofile 介绍
:description: Helidon Microprofile introduction
:keywords: helidon, microprofile, micro-profile

MicroProfile是Java EE开发人员熟悉的平台定义。如果您有使用JAX-RS，JSON-P和CDI的经验，则可能更喜欢使用此模型。

要扩展MicroProfile应用程序的功能，您可能还决定使用Helidon核心API，尤其是配置和安全性。

== Helidon MicroProfile入门

开始使用MicroProfile应用程序，需要完成以下任务：

=== Maven 依赖

在项目中声明以下依赖项：

[source,xml]
.Maven 依赖
----
<dependency>
  <groupId>io.helidon.microprofile.bundles</groupId>
  <artifactId>helidon-microprofile-1.1</artifactId>
</dependency>
----

=== 项目文件

使用至少一个资源方法创建JAX-RS Resource类。

[source,java]
.JAX-RS 资源类举例
----
@Path("/")
@RequestScoped
public class HelloWorldResource {
    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String message() {
        return "Hello World";
    }
}
----

并创建一个JAX-RS应用程序
[source,java]
.JAX-RS Application举例
----
@ApplicationScoped
@ApplicationPath("/")
public class HelloWorldApplication extends Application {
    @Override
    public Set<Class<?>> getClasses() {
        return Set.of(
                HelloWorldResource.class
        );
    }
}
----

在 `src/main/resources/META-INF` 中添加 `beans.xml` ，以便CDI实现可以获取您的类。

[source,xml]
.beans.xml
----
<?xml version="1.0" encoding="UTF-8"?>
<beans/>
----

最后一步，在应用程序（或专用的Main类）中添加一个main方法来启动所有操作。

[source,java]
.JAX-RS 应用举例
----
public static void main(String[] args) {
    io.helidon.microprofile.server.Main.main(args);
}
----

运行主类。服务器将从端口7001启动并为您的资源提供服务。

=== 添加 Jandex

Jandex是Weld（CDI实现）的索引工具，有助于加快应用程序的启动时间。

要使用Jandex，请配置一个Maven插件，该插件将索引添加到JAR文件并依赖于Jandex。

[source,xml]
.jandex 依赖
----
<dependency>
    <groupId>org.jboss</groupId>
    <artifactId>jandex</artifactId>
    <version>2.0.4.Final</version>
</dependency>
----

[source,xml]
.jandex 插件配置
----
<build>
    <plugins>
        <plugin>
            <groupId>org.jboss.jandex</groupId>
            <artifactId>jandex-maven-plugin</artifactId>
            <version>1.0.5</version>
            <executions>
                <execution>
                    <id>make-index</id>
                    <goals>
                        <goal>jandex</goal>
                    </goals>
                    <phase>process-classes</phase>
                </execution>
            </executions>
        </plugin>
    </plugins>
</build>
----
