///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2018 Oracle and/or its affiliates. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= 配置服务器
:description: Helidon MicroProfile server configuration
:keywords: helidon, microprofile, micro-profile

默认情况下，服务器使用MicroProfile配置，但您可能还想使用Helidon配置。

== 配置服务器

有3个默认的MicroProfile配置源：

* `System.getProperties()`
* `System.getenv()`

* 所有 `META-INF/microprofile-config.properties` 文件都在类路径下

I在此示例中，配置位于文件中，并包含Helidon配置选项。

[source,properties]
.META-INF/microprofile-config.properties - 服务器配置
----
# 默认是localhost
server.host=some.host
# 默认是7001
server.port=7011

# Helidon配置（可选）

# 传入连接的队列长度。默认值为1024
server.backlog: 512
# TCP接收窗口。默认值为0以使用实现默认值
server.receive-buffer: 256
# 套接字超时毫秒 - 默认为0（无限）
server.timeout: 30000
# 默认值为CPU_COUNT * 2
server.workers=4
# 默认关闭了SSL
ssl:
 private-key:
    keystore-resource-path: "certificate.p12"
    keystore-passphrase: "abcd"
----

对于Helidon配置，默认文件是类路径上的 `application.yaml` （例如 src/main/resources/application.yaml）。

[source,yaml]
.application.yaml - 服务器配置
----
server:
  sockets:
    - secure:
        port: 443
        # supports all socket related properties of server
        backlog: 1024
        receive-buffer: 0
        timeout: 60000
        ssl:
          ....
    - another:
        port: 12041
----
