///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2018 Oracle and/or its affiliates. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= 配置应用程序
:description: Helidon MicroProfile application configuration
:keywords: helidon, microprofile, micro-profile

您的应用程序可以使用MicroProfile配置或Helidon配置（或两者）。
MicroProfile Config为其他MicroProfile服务器提供了可移植性。
Helidon Config支持完整的树结构，包括重复元素。

== 配置应用程序

您可以从MicroProfile配置和Helidon配置中注入应用程序可以访问的值。

[source,java]
.JAX-RS - 注入一个配置属性
----
@Inject
public MyResource(@ConfigProperty(name="app.name") String appName) {
    this.applicationName = appName;
}
----

您还可以注入整个配置实例， `io.helidon.config.Config` 或者
 `org.eclipse.microprofile.config.Config`.
[source,java]
.JAX-RS - 注入配置
----
@Inject
public MyResource(Config config) {
    this.config = config;
}
----
