///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2018 Oracle and/or its affiliates. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= 配置密钥
:description: Helidon MicroProfile configuration secrets
:keywords: helidon, microprofile, micro-profile

当安全性需要具有重复复杂元素的配置时，请使用Helidon Config。

此示例配置基本身份验证提供程序并保护Web服务器上的静态内容。它还包括Jersey的注释。

== 保护静态内容

[source,yaml]
.application.yaml
----
security:
  providers:
    # 基于属性的访问控制，验证角色
    - abac:
    # HTTP基本认证
    - http-basic-auth:
        realm: "helidon"
        users:
          - login: "jack"
            password: "password"
            roles: ["user", "admin"]
          - login: "jill"
            password: "password"
            roles: ["user"]
          - login: "john"
            password: "password"
  # 保护静态内容 - 需要经过身份验证的用户
  web-server:
    paths:
      - path: "/static-cp[/{*}]"
        authenticate: true
----

=== 保护配置密钥

如果未向MicroProfile服务器提供Helidon Config的显式实例，则**默认情况下会启用**安全配置筛选器。
但是，如果不进行配置，则安全配置筛选器仅支持别名模板，以检查是否存在明文密码 (template ${CLEAR=...}.

添加安全配置筛选器：

[source,java]
.Add secure config filter
----
Config helidonConfig = Config.builder()
    .addFilter(SecureConfigFilter.fromConfig())
    .build();
----

将加密值放入配置文件中，以便将其存储在公共存储库中，而不会暴露密钥值。
请务必使用强密密码。

支持的模板是：

.模版
[cols="1,3,5"]
|===
|模版 |描述 |举例

|${CLEAR=...}
|Secret in clear text (for testing) - `requiresEncryption` must be disabled
|${CLEAR=knownSecret}

|${RSA=...}
|Public/private key encryption, base64 value
|${RSA=aGr3sFCMQznixrgbIk9qNfoLnO1cdi3H86qweCNjxFvH4dYg5IQM1EuoyTjJaXcSCG5MBskpeA3bjnWYrzeAFFlZHuYSPsb+wJVzGLrfUColTn+BPJjpJ3rmEd3AVkJl1ASfBBMh3q3deC+rvUdhfoTGBO8sC0teUATklCQSxfHOnIxswxqrplnoGXToGiTIfehiN2IZNulRKeoDQ0AeoKREmq5au4L8OOmS+D9BqnlKMc0F1tULZ7+h3Cxla4lXC5WRPoPfHBU4vzRZOGzeDvLkRgrD60caw/wKn5M0Wy1A1cKR8E46ceBXCjJ2eWIcLyhZSAZWDe3ceNrawHZtCg==}

|${AES=...}
|Shared secret ecryption, base64 value
|${AES=D/UgMzsNb265HU1NDvdzm7tACHdsW6u1PjYEcRkV/OLiWcI+ET6Q4MKCz0zHyEh9}

|${ALIAS=...}
|Reference to another key
|${ALIAS=someOtherKey}
|===

=== 需要加密

安全配置过滤器有一个选项，用于定义是否需要加密。如果它设置为true（默认值），那么：

* 使用$ {CLEAR = ...}模板的配置值将在请求时导致异常。
* 如果配置了 `security.config.aes.insecure-passphrase` ，则在引导期间过滤器会失败。

=== 使用对称加密（AES）
对称加密基于加密人员已知的public密钥，并且还提供给应用程序。

==== 加密值（AES）

安全配置筛选器提供了可用于加密值的主类：`io.helidon.security.tools.config.Main`

[source,bash]
.使用共享密钥  `masterPassword` 加密秘密 `secretToEncrypt`.
----
java io.helidon.security.tools.config.Main aes masterPassword secretToEncrypt
----

该工具将要输入的字符串作为属性值返回到配置中。

==== 共享密钥（AES）

您可以通过以下几种方式提供共享密钥：

- 在配置中 - 仅用于测试/演示目的 - key是  `security.config.aes.insecure-passphrase`
- 作为环境变量 - `SECURE_CONFIG_AES_MASTER_PWD`

=== 使用非对称加密（RSA）
这种方法基于一对密钥，任何人都知道的公钥，以及有限的一方知道的私钥（通常是一个人或一个过程）。对于非对称加密，以下情况属实：

- 由公钥加密的值只能由私钥解密
- 由私钥加密的值只能由公钥解密

使用安全配置筛选器时，应使用公钥加密配置值，并授予应用程序进程访问私钥以解密值的权限。

==== 加密值（RSA）
安全配置筛选器提供了可用于加密值的主类：`io.helidon.security.tools.config.Main`

[source,bash]
.使用密钥库中的公共证书加密密码 `secretToEncrypt`
----
java io.helidon.security.tools.config.Main rsa /path/to/keystore.p12 keystorePassword publicCertAlias secretToEncrypt
----

该工具将要输入的字符串作为属性值返回到配置中。

==== 配置安全配置过滤器（RSA）

您可以配置私钥的属性。这些密钥以 `security.config.rsa` 为前缀。


.RSA配置选项：密钥库
[cols="2,2,3,5"]
|===
|What |配置 Key |环境变量|

|Keystore path
|`keystore-path`
|`SECURE_CONFIG_RSA_PRIVATE_KEY`
|Keystore is located in file system

|Keystore
|`keystore-resource-path`
|N/A
|Keystore is located on classpath

|Private key alias
|`key-alias`
|`SECURE_CONFIG_PRIVATE_KEY_ALIAS`
|Alias of the private key (such as "1", which is usually the default)

|Keystore passphrase
|`keystore-passphrase`
|`SECURE_CONFIG_PRIVATE_KEYSTORE_PASSPHRASE`
|Password for the keystore (and private key).
|===

.RSA配置选项：PEM（PKCS＃8）私钥
[cols="2,2,3,5"]
|===
|What |配置 Key |环境变量|描述

|Path
|`pem-key-path`
|`SECURE_CONFIG_RSA_PEM_KEY`
|Key is located on file system

|Resource path
|`pem-key-resource-path`
|N/A
|Key is located on classpath

|Passphrase
|`pem-key-passphrase`
|`SECURE_CONFIG_PRIVATE_KEY_PASSPHRASE`
|Password protecting the private key
|===

[source,yaml]
.yaml 配置举例
----
security.config:
  # Set to true for production - if set to true, clear text passwords will cause failure
  require-encryption: false
  # The "master" password for AES decryption. For production, set this via system property or environment variable.
  aes.insecure-passphrase: "myMasterPasswordForEncryption"
  # See documentation of pki-util
  rsa:
    # load from classpath
    keystore-resource-path: ".ssh/keystore.p12"
    # If keystore is used, alias to use from the keystore (in this example, it is "1")
    key-alias: "1"
    # Password of keystore
    keystore-passphrase: "helidon"
----
