///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2018 Oracle and/or its affiliates. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= 介绍
:description: about Helidon
:keywords: helidon, java, microservices, microprofile

== 介绍

Helidon是用于开发微服务的一个Java库集合。
没有唯一的工具或部署模型。你的微服务只是一个简单的Java SE 应用程序。

Helidon的基础由三部分组成：

[PILLARS]
====

[CARD]
.WebServer
[icon=settings_ethernet]
--
由Netty提供支持并具有响应式功能的编程HTTP API。
--

[CARD]
.Config
[icon=settings]
--
灵活的配置框架，支持多种源和格式。
--

[CARD]
.Security
[icon=security]
--
用于处理身份验证，授权和上下文传播的工具链。
--
====

== MicroProfile

在此基础之上，Helidon支持MicroProfile系列API，包括JAX-RS和CDI。这意味着您可以从以下两种编程模型中选择一种：

 * Helidon SE: 一种函数式编程风格，直接使用Helidon WebServer，Config和Security API。这种方式将控制权全权交给你自己。
 * Helidon MP: 这是一种对Java EE程序员来说很熟悉的一种方式，此方式支持https://microprofile.io[MicroProfile] API等一系列更具说明性的模型。这对Java EE开发人员来说很熟悉。

我们的<<getting-started/02_base-example.adoc,快速入门示例>>可让您开始使用这些编程模型中的任何一种。

=== 支持Docker和Kubernetes
<<getting-started/02_base-example.adoc,Helidon 快速入门示例>>包含对Docker和Kubernetes的支持。只需按照示例操作，您就可以在几分钟内完成并运行简单的服务。
