///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2018 Oracle and/or its affiliates. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Introduction
:description: about Helidon
:keywords: helidon, java, microservices, microprofile

== Introduction

Helidon是用于开发微服务的一个Java库集合。
没有唯一的工具或部署模型。你的微服务只是一个简单的Java SE 应用程序。

Helidon的基础由三部分组成：

[PILLARS]
====

[CARD]
.WebServer
[icon=settings_ethernet]
--
由Netty提供支持并具有响应式功能的编程HTTP API。
--

[CARD]
.Config
[icon=settings]
--
灵活的配置框架，支持多种源和格式。
--

[CARD]
.Security
[icon=security]
--
用于处理身份验证，授权和上下文传播的工具链。
--
====

== MicroProfile

On top of this foundation Helidon supports the MicroProfile family of APIs,
 including JAX-RS and CDI. This means you can choose from one of two
 programming models:

 * Helidon SE: a functional programming style that uses the Helidon WebServer,
               Config and Security APIs directly. This gives you full
               transparency and control.
 * Helidon MP: a more declarative model that supports the https://microprofile.io[MicroProfile]
               family of APIs. This will be familiar to Java EE developers.

Our <<getting-started/02_base-example.adoc,Quickstart Examples>> gets
you started using either of these programming models.

=== Docker and Kubernetes support

The <<getting-started/02_base-example.adoc,Helidon Quickstart Examples>> contain
support for Docker and Kubernetes. Just follow the examples and you'll have
a simple service up and running in minutes.
